{% set version = "4.3.0" %}
{% set sha256 = "8a33cb7b1ef47f2d6dc16e9cf971217d5a4882a3541c070e78a0e8e8edcb3f82" %}

package:
  name: traitlets
  version: {{ version }}

source:
  fn: traitlets-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/t/traitlets/traitlets-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
  run:
    - python
    - ipython_genutils
    - six
    - decorator
    - enum34

test:
  imports:
    - traitlets
    - traitlets.config

about:
  home: http://ipython.org/
  license: BSD 3-clause
  summary: Configuration system for Python applications

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - scorlay
