{% set version = "5.0.0" %}

package:
  name: traitlets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/traitlets/traitlets-{{ version }}.tar.gz
  sha256: 0d9c4005506b306b0a99551e96174b8bedc675c2dd048f92b3bbbb7d86ac93a9

build:
  noarch: python
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  build:
    - python
    - pip
  run:
    - python
    - ipython_genutils

test:
  imports:
    - traitlets
    - traitlets.config

about:
  home: http://traitlets.readthedocs.org/
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: Configuration system for Python applications

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - SylvainCorlay
    - ocefpaf
    - Carreau
    - takluyver
    - rmorshea
