{% set version = "5.0.5" %}

package:
  name: traitlets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/t/traitlets/traitlets-{{ version }}.tar.gz
  sha256: 178f4ce988f69189f7e523337a3e11d91c786ded9360174a3d9ca83e79bc5396

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - ipython_genutils

test:
  imports:
    - traitlets
    - traitlets.config

about:
  home: http://traitlets.readthedocs.org/
  license: BSD-3-Clause
  license_file: COPYING.md
  summary: Configuration system for Python applications
  description: |
    Traitlets is a framework that lets Python classes have attributes with
    type checking, dynamically calculated default values, and "on change"
    callbacks.
  dev_url: https://github.com/ipython/traitlets
  doc_url: http://traitlets.readthedocs.org/en/stable/
  doc_source_url: https://github.com/ipython/traitlets/blob/master/docs/source/index.rst

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - minrk
    - SylvainCorlay
    - ocefpaf
    - Carreau
    - takluyver
    - rmorshea
    - blink1073
    - zsailer
