# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "gNneu7Gdx16AD/EMpDjTzWh5haqXA/Adf2s0GYIRH7AF3f7lf2DgM2PBB9QejcKsmKs/YZ4q1UAaMipOPR4zGuklhtyU1v9+8MbOirJQll34C+ejRJdA5B10zVl+NCRHuS77vKmyx+Jtau0MztWWeYn/UIOPhtkNqfEbUcUwKefsKZRH+tHIAaHyf/o5R+3MnJ4WgWXXXRQOAjLGXE4U194i1E4th6rvckrfVhLw2J5fQnm/XwOmbydYFNU1xHKUoImE0+DoQ4j2+JABZX3uO0CXfSL3IFNk2dfeRQabJyjlbjgWYp3hkiQdrx3jYSeqmq4+5vVxZEt7dmKn1gLhfuzsKrBeZOwnGI9OwRFJ0mEF9wH1RQCXBEuqaRNjHjLFjnpMvHUNziQByon+55LBabHAqXl1NjBDhhfHmGaLsgxU51adUf5NE+CeouA3WkIxJSs8CoCF++k6UnlF3rK3igv4UKo0Z0vZgnjUVmbMcuGF01V7g5jkVB5MCHTkdDsAV4Uh6g9xurZZ1Gq+6dD2c1oJ8ikyt3ygZbrzT69t+SKqe7wHzRnqW8gW5WRZooR4ZI5Y9uf+dk7aG36a9N43B7/H/H+q/A3rqNQhepmGpBLet/Tq6jefgma8o/NlAdLLeeTJfd08/Q/2mMa+CREDcm2yQTe7u2SoIQfNMzHott8="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
