travis:
  secure:
    BINSTAR_TOKEN: UH75hw5udC8mc+dw7JPvLnWtybwkST6pzWYgOOs9NN+q8W8WXrZ3sPnp7Rp4h3aT8MazNr34PbVQYfUF9gh+yxC94tmaktk4o3/1g6c8HNCWqL++5tIopwYQlMvJX7sCPqA+gARJMuyOH6l7vhYB3mwuYOjUEXMHay76MAyKr+qGLPxng9KRAUGk9pCtvA7gwk/uPvsglxJLCWP0ZpB8j8W2ur/TGem/s4DsbymAjbq2+NgWV37EqTfL5g/oivdIYSNbSeMcLL0e9od+qPeXiOxAx1Eydhbvun+gjKk3x3qsg7U28HdkZIFSS05KBdBg1N+gguHeGMldFZuIM8bKkIiiQANt7n5MOhFcS8sJNllsKIJwspLtvCO981qD799RfPH+gBTE4P9ak8EuomrJkZNuoHyGzkOt/SwHUAAxIbupwCdhakDA0GnaGDzIdD/j2u354b9h372STWuEx9ji+d72CgvBZt5mouBbYuKqxc8ET1i1yHI5g4NWDd7s4UzabnQch1JTCr+Ffo0/uRganmLJD0CWCBTjBIi6rPG1olaMpylB8tZU+WjljVdG5DOS1fejocctNrZNp2e+J4LIm7Pta1MFvi9zj9G775e9HEc8O+NtRzwcwU9Bvougo2Ifq4QB3aM8SOEhSRIgNgGiBL04giD4zzXedt2FPmGCZ+0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
